# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='Unknown Mix', max_length=255),
        ),
    ]
