# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20190108_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b', max_length=3),
        ),
    ]
