# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-01-08 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_auto_20190108_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(max_length=3),
        ),
    ]
